version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: my-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: RE_DB
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
